# Generated by Django 2.0.1 on 2018-01-19 04:14

import django.core.validators
from django.db import migrations, models
import helper.day_of_week


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vacation_mode', models.BooleanField(default=False)),
                ('days_away', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('system_alarm', models.BooleanField(default=False)),
                ('system_alarm_time', models.TimeField()),
                ('time_of_day', models.TimeField()),
                ('current_day_of_week', helper.day_of_week.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('current_date', models.DateField()),
                ('auto_dst', models.BooleanField(default=True)),
            ],
        ),
    ]
